version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  flyway:
    image: flyway/flyway:9
    container_name: flyway_migration
    depends_on:
      - postgres
    command:
      - -url=jdbc:postgresql://postgres:5432/mydb
      - -user=admin
      - -password=admin123
      - migrate
    volumes:
      - ./db/migration:/flyway/sql
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network: